use customer_behaviour_project

select * from customer_behaviour 

--Total revenue generated by male vs female customers 

select gender, sum(purchase_amount) as revenue 
from customer_behaviour
group by gender 

--Checking which customer used a Promo code but still spent more than the average purchase amount 
select customer_id, purchase_amount
from customer_behaviour
where promo_code_used = 'Yes' and purchase_amount >= AVG(purchase_amount)

--Checking top 5 items with ths highest average review rating 
select top 5
item_purchased, ROUND(avg(review_rating),2) as highest_review_rating 
from customer_behaviour
group by item_purchased 
order by avg(review_rating) desc

--Comparing ths average purchase amount between standard and express shipping 
select shipping_type, avg(purchase_amount) as average_purchase 
from customer_behaviour
where shipping_type in ('Standard', 'Express')
group by shipping_type 

--Checking wheather subscribed customers spend more and comparing average spent and total revenue between subscibers abd non-subscribers 
select  subscription_status,
count(customer_id) as total_customer, 
avg(purchase_amount) as average_spent,
sum(purchase_amount) as total_revenue
from customer_behaviour 
group by subscription_status
order by total_revenue, average_spent



--Checking which 5 product has the highest percentages of purchases with promo code used 
select top 5
item_purchased, 
100 * sum(
	CASE WHEN promo_code_used = 'Yes'
		 THEN 1
		 ELSE 0
		 END)/ count(*) as discount_rate
from customer_behaviour
group by item_purchased 
order by discount_rate desc

--Segmenting customers into New, Returning and Loyal based on their total number of prevoious purchases and show the count of each segments 
with customer_type as(
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'NEW'
	WHEN previous_purchases between 2 and 10 THEN 'RETURNING'
	ELSE 'LOYAL'
	END as customer_segments 
from customer_behaviour
)

select customer_segments, count(*) as Number_of_customer
from customer_type
group by customer_segments

--Checking top 3 most purchased products within each categories 
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer_behaviour
group by category, item_purchased
)
select category, item_purchased, total_orders, item_rank
from item_counts
where item_rank <= 3

--checking customers who are repeat buyers(More than 5 previous purchases) also likely to subscribe

select subscription_status,
count(customer_id) as repeat_buyers
from customer_behaviour
where previous_purchases > 5
group by subscription_status

--checking revenue contribution of each age group
select age_group, 
sum(purchase_amount) as total_revenue
from customer_behaviour
group by age_group
order by age_group desc